### ISSUE TITLE
EULA and Copyright

### ISSUE THREAD

**Issue by dedok** [tarantool/zookeeper#1]
Add EULA [1], Copyright [1] and BSD v2 license. A good example could be found at the repo [2]

[1] if libzookeer has it (based on https://github.com/forhappy/zklua).
[2] https://github.com/tarantool/mqtt

**Comment by bigbes** [comment]
Probably the right terms are EULA and Copyright. Copyright isn't the right term for this, since BSD is "permissive free license".

BTW: EULA isn't the right term too, since it's mostly used for proprietary software

**Comment by dedok** [comment]
Thx you @bigbes, mistyped was fixed. EULA and (C) should be added, if libzookeeper has it.
