### ISSUE TITLE
Installation. Dependences.

### ISSUE THREAD

**Issue by seet61** [tarantool/zookeeper#6]
When I tried install module I got a error:
`# tarantoolctl rocks install zookeeper
Warning: Failed searching manifest: Failed fetching manifest for http://rocks.tarantool.org/ - Failed downloading http://rocks.tarantool.org/manifest - /root/.cache/luarocks/http___rocks.tarantool.org_/manifest
Warning: Failed searching manifest: Failed fetching manifest for http://rocks.tarantool.org/ - Failed downloading http://rocks.tarantool.org/manifest - /root/.cache/luarocks/http___rocks.tarantool.org_/manifest
Warning: Failed searching manifest: Failed fetching manifest for http://rocks.tarantool.org/ - Failed downloading http://rocks.tarantool.org/manifest - /root/.cache/luarocks/http___rocks.tarantool.org_/manifest

Error: No results matching query were found.`

After that:
`# tarantoolctl rocks install https://raw.githubusercontent.com/tarantool/rocks/gh-pages/zookeeper-scm-1.rockspec
Cloning into 'zookeeper'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 41 (delta 2), reused 29 (delta 2), pack-reused 0
Unpacking objects: 100% (41/41), done.
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found TARANTOOL: /usr/include (found version "1.10.2-178-gfb0c5a0c1")
-- Tarantool LUADIR is /var/tmp/.rocks/share/tarantool/rocks/zookeeper/scm-1/lua
-- Tarantool LIBDIR is /var/tmp/.rocks/share/tarantool/rocks/zookeeper/scm-1/lib
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Zookeeper (missing: Zookeeper_LIBRARY Zookeeper_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindZookeeper.cmake:40 (find_package_handle_standard_args)
  CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_zookeeper-scm-1-mCtPax/zookeeper/build.luarocks/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed cmake.`

Problem solution:
`apt-get install zookeeper libzookeeper-st-dev`

Please add this to documentation, it would be usefull for other users.

**Comment by Totktonada** [comment]
The first one looks as a temporary network issue (the URLs available for me).

I'll add dependencies to README.
